### PR TITLE
add Tableau-Prep-Builder chocolatey package

### PR DESCRIPTION
**Pull request by jan-win1993**

### CODE REVIEW

**Comment by tlourey** [comment]
@meek2100 any chance of getting this pull request approved and merged? :) Many thanks.

**Comment by meek2100** [comment]
Yes, I've tested this, merged it in, and it has been submitted to Chocolatey for review.   Thanks for putting this together, let me know if you'd like to be added as a maintainer for it on Chocolatey.

Here is the Chocolatey package URL: https://chocolatey.org/packages/Tableau-Prep-Builder/2021.1.1

**Comment by fraenki** [comment]
@meek2100 Thanks for merging this PR. The package is failing chocolatey's tests, could you probably fix this? Thanks :)

**Comment by meek2100** [comment]
@fraenki,
This is just waiting on a moderator to review it and approve it to have a permanent expectation for the 2nd test.  Similar to Tableau Desktop (https://chocolatey.org/packages/Tableau-Desktop). The issue is the 2nd test on Chocolatey will always fail due to a reboot that is required after installing the dependencies on their test environment, specifically  Visual C++ 2017 Redistributable.  

The initial review takes a while for whatever reason, but once it has been given the exception then future updates will roll out much quicker.

You can still install it on a system while it is under review by calling the specific version in your Choco install command like this: "choco install tableau-prep-builder --version=2021.1.1".  Note that it will give you a warning that it might be unsafe or broken since the review process hasn't been completed yet.

**Pull request merged**
